"""add session token and admin flag to user

Revision ID: ff1026526630
Revises: ebd315190ba7
Create Date: 2018-04-27 23:28:15.109148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff1026526630'
down_revision = 'ebd315190ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('session_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session_token')
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
